"use strict";

module.exports = {
  siteUrl: "https://not-another-devlog.netlify.com",
  url: "https://not-another-devlog.netlify.com",
  title: "Not Another Devlog?!",
  tagline: "The Development Blog of Thomas Leon Highbaugh. A place for honest, on-the-ground takes on technologies used in development and the art of developing software on Linux computers.",
  copyright: '© 2019 [TLH], All rights reserved',
  author: {
    name: "Thomas Leon Highbaugh",
    bio: "Autodidactic Web Developer & Linux Madman",
    contacts: {
      linkedin: "https://www.linkedin.com/in/thomas-leon-highbaugh",
      github: "https://github.com/Thomashiughbaugh",
      twitter: "https://twitter.com/thomashighbaugh",
      portfolio: "https://thomasleonhighbaugh.me",
      gallery:"https://netlify.com",
      dribbble:"https://dribbble.com/thighbaugh"
    },
  },
  labels: [
    {
      tag: "react",
      tech: "React",
      name: "DiReact",
      size:'0.5rem',
      color: "#67cdcc",
    },
    {
      tag: "nodejs",
      tech: "Node.js",
      name: "DiNodejsSmall",
      size:'0.5rem',
      color: "#7ec699",
    },
    {
      tag: "git",
      tech: "Git",
      name: "DiGitMerge",
      size:'0.5rem',
      color: "#e5e5e5",
    },
    {
      tag: "javascript",
      tech: "JavaScript",
      name: "DiJsBadge",
      size:'0.5rem',
      color: "#f8c555",
    },
    {
      tag: "css",
      tech: "CSS",
      name: "DiCss3Full",
      size:'0.5rem',
      color: "#00bcd4",
    },
    {
      tag: "python",
      tech: "Python",
      name: "DiPython",
      size:'0.5rem',
      color: "#ffab00",
    },
    {
      tag: "ruby",
      tech: "Ruby",
      name: "DiRuby",
      size:'0.5rem',
      color: "#e2777a",
    },
    {
      tag: "gatsby",
      tech: "Gatsby",
      name: "DiJekyllSmall",
      size:'0.5rem',
      color: "#cc99cd",
    },
    {
      tag: "html",
      tech: "HTML",
      name: "FaHtml5",
      size:'0.5rem',
      color: "#f8c555",
    },
    {
      tag: "php",
      tech: "php",
      name: "DiPhp",
      size:'0.5rem',
      color: "#3f51bf",
    },
    {
      tag: "linux",
      tech: "Linux",
      name: "DiLinux",
      size:'0.5rem',
      color: "#9063ec",
    },
    {
      tag: "spacemacs",
      tech: "SpaceMacs",
      name: "DiVim",
      size:'0.5rem',
      color: "#ff9cff",
    },
    {
      tag: "scss",
      tech: "SCSS",
      name: "FaSass",
      size:'0.5rem',
      color: "#6FFFFF",
    },
  ],
}
